FROM andreisamuilik/php5.5.9-apache2.4-mysql5.5

ADD src /app/
RUN apt-get update --fix-missing
RUN apt-get install -y apache2
RUN apt-get install -y php5 
RUN apt-get install -y libapache2-mod-php5
RUN a2enmod rewrite

COPY sql.sql /tmp/sql.sql
COPY src/* /var/www/html/
COPY run.sh /run.sh
 
RUN chmod +x /run.sh
RUN chmod 777 /var/www/html

EXPOSE 80

CMD ["/run.sh"]
